[package]
name = "chat_shared"
version = "0.1.0"
edition = "2021"
authors = ["Phill030"]

[dependencies]
async-trait = "0.1.73"
crc32fast = "1.3.2"
tokio = { version = "1.32.0", features = ["full"] }
